# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    groups:
      pip:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
  - package-ecosystem: github-actions
    directory: /
    groups:
      # group official actions updates
      actions:
        patterns:
          - "actions/*"
      redhat-actions:
        patterns:
          - "redhat-actions/*"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
