repos:
  - repo: https://github.com/ambv/black
    rev: 21.8b0
    hooks:
      - id: black
        args: [--target-version=py36]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        # default black line length is 88
        args: [--max-line-length=88]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.0
    hooks:
      - id: prettier
